name: screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Take Screenshot TEPCO billing
        id: screenshot
        uses: ./
        with:
          officeCode: ${{ secrets.OFFICE_CODE }}
          visitNumber1: ${{ secrets.VISIT_NUMBER1 }}
          visitNumber2: ${{ secrets.VISIT_NUMBER2 }}
          visitNumber3: ${{ secrets.VISIT_NUMBER3 }}
          visitNumber4: ${{ secrets.VISIT_NUMBER4 }}
          zipCode1: ${{ secrets.ZIP_CODE1 }}
          zipCode2: ${{ secrets.ZIP_CODE2 }}
          prefecture: ${{ secrets.PREFECTURE }}
          city: ${{ secrets.CITY }}
          address1: ${{ secrets.ADDRESS1 }}
          address2: ${{ secrets.ADDRESS2 }}
          addressBanch: ${{ secrets.ADDRESS_BANCHI }}
          addressGou: ${{ secrets.ADDRESS_GOU }}
          addressRoomNm: ${{ secrets.ADDRESS_ROOM_NM }}
          options: ${{ secrets.OPTIONS }}
          firstName: ${{ secrets.FIRST_NAME }}
          lastName: ${{ secrets.LAST_NAME }}
          companyName: ${{ secrets.COMPANY_NAME }}
          departmentName: ${{ secrets.DEPARTMENT_NAME }}
          phoneNumber1: ${{ secrets.PHONE_NUMBER1 }}
          phoneNumber2: ${{ secrets.PHONE_NUMBER2 }}
          phoneNumber3: ${{ secrets.PHONE_NUMBER3 }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
